# Generated by Django 4.1.13 on 2025-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
